version: 2.1
orbs:
  docker: circleci/docker@2.2.0



jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [ app-build ]
      - run:
          name: Build app
          command: |
            cd app
            npm install
      - save_cache:
          paths: [ app/node_modules ]
          key: app-build
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [ app-lint ]
      - run:
          name: Lint app
          command: |
            cd app
            npm install
            npm run lint
      - save_cache:
          paths: [ app/node_modules ]
          key: app-lint
  build_docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build and Push Docker Image to ECR
          command: |
            cd app
            
            # Build the Docker image
            docker build -t your-image:latest .
            
            # Tag the Docker image with ECR repository URI
            ECR_REPOSITORY="609874051346.dkr.ecr.us-east-1.amazonaws.com"
            docker tag lampqt:latest $ECR_REPOSITORY
            
            docker build -t ${ECR_URL}:latest .
            docker push ${ECR_URL}:latest
            
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker push $ECR_REPOSITORY

workflows:
  default:
    jobs:
      - build
      - lint:
          requires: [build]
      - build_docker:
          requires: [lint]
