version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  create-cluster:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install
          command: |
            # Install AWS CLI
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            # Install eksctl
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            
            # Install kubectl
            curl --silent --location "https://dl.k8s.io/release/$(curl --silent --location https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" --output kubectl
            sudo install kubectl /usr/local/bin/
            
            # Verify installations
            aws --version
            eksctl version
            kubectl version --client
      - run:
          name: Create EKS cluster
          command: |
            # Set the name of the cluster
            CLUSTER_NAME="lampqt-cluster"
            
            # Check if the cluster already exists
            if aws eks describe-cluster --name "$CLUSTER_NAME" >/dev/null 2>&1; then
              echo "The EKS cluster '$CLUSTER_NAME' already exists."
            else
              # Create the EKS cluster
              eksctl create cluster -f eks/cluster.yaml
              kubectl get nodes
            fi

      - run:
          name: Move config file to s3
          command: |
            aws s3 cp s3://bucket-name/path/to/kubeconfig ~/.kube/config
      - save_cache:
          paths:
            - ~/.kube/config
          key: kubeconfig-{{ .Branch }}

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [ app-build ]
      - run:
          name: Build app
          command: |
            cd app
            npm install
      - save_cache:
          paths: [ app/node_modules ]
          key: app-build
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [ app-lint ]
      - run:
          name: Lint app
          command: |
            cd app
            npm install
            npm run lint
      - save_cache:
          paths: [ app/node_modules ]
          key: app-lint
  build_docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - run:
          name: Build and Push Docker Image to ECR
          command: |
            cd app
            
            # Build the Docker image
            docker build -t lampqt .
            
            # Tag the Docker image with ECR repository URI
            ECR_REPOSITORY="609874051346.dkr.ecr.us-east-1.amazonaws.com/lampqt:latest"
            docker tag lampqt:latest $ECR_REPOSITORY
            
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 609874051346.dkr.ecr.us-east-1.amazonaws.com
            docker push $ECR_REPOSITORY


  deploy:
    docker:
      - image: bearengineer/awscli-kubectl
    steps:
      - checkout
      - restore_cache:
          keys:
            - kubeconfig-{{ .Branch }}
      - run:
          name: Set kubeconfig path
          command: |
            export KUBECONFIG=$HOME/.kube/config
      - run:
          name: Get pods
          command: kubectl get pods
      - run:
          name: Deploy Docker Image to EKS Cluster
          command: |
            kubectl create namespace lampqt-capstone
            NS=$(kubectl get namespace lampqt-capstone | awk '{print $1}' | grep -v NAME)
            echo $NS
            if [ "$NS" = "lampqt-capstone" ]
            then
              echo "Namespace exists"
            else
              echo "Creating Namespace"
              kubectl create namespace lampqt-capstone
            fi
            kubectl apply -f app/deployment.yml
            LB_URL=$(kubectl get services -l lampqt-service -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')
            echo "Load Balancer URL: $LB_URL"



workflows:
  default:
    jobs:
      - create-cluster
      - build
      - lint:
          requires: [build]
      - build_docker:
          requires: [lint, create-cluster]
      - deploy:
          requires: [ build_docker]
