apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lampqt-cluster
  region: us-east-1
  version: '1.26'

availabilityZones: ["us-east-1a", "us-east-1b"]

nodeGroups:
  - name: lampqt-nodegroup
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 20

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
